import Link from 'next/link.js';
import Navbar from '../components/Navbar.jsx';
import { Montserrat } from 'next/font/google';
import './styles.css';

export const metadata = {
  title: 'Nextjs practice',
  description: 'Generated by Lautaro Nasello',
};
const montserrat = Montserrat({
  weight: ['100', '300', '500', '800'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
});
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
