import CharacterCard from '../../components/CharacterCard/CharacterCard.jsx';
import styles from './styles.module.css';

export const metadata = {
  title: 'Characters grid',
  description: 'Generated by Lautaro Nasello',
};

async function loadCharacters(page) {
  const res = await fetch(
    `https://rickandmortyapi.com/api/character?page=${page}`
  );
  const data = await res.json();
  await new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve();
    }, 2000);
  });
  return data;
}

export default async function Characters({ filterQty = 8, page = 1 }) {
  const res = await loadCharacters(page);
  return (
    <div>
      <h1>These are the Characters</h1>
      <div className={styles.bodyCharacter}>
        {res.results.slice(0, filterQty).map((character) => (
          <div key={character.id}>
            <CharacterCard
              image={character.image}
              name={character.name}
              location={character.location.name}
              status={character.status}
              id={character.id}
            />
          </div>
        ))}
      </div>
    </div>
  );
}
